WITH base_data AS (
    SELECT 
        DECODE(x.gte_0, 'FAC', y.sdhnum_0, 'FCP', y.sdhnum_0, 'AVC', y.srhnum_0, 'AVP', y.srhnum_0) AS piece_raw,
        DECODE(x.gte_0, 
            'FAC', (SELECT dlvdat_0 FROM sdelivery WHERE sdhnum_0 = DECODE(x.gte_0, 'FAC', y.sdhnum_0, 'FCP', y.sdhnum_0, 'AVC', y.srhnum_0, 'AVP', y.srhnum_0)), 
            'FCP', (SELECT dlvdat_0 FROM sdelivery WHERE sdhnum_0 = DECODE(x.gte_0, 'FAC', y.sdhnum_0, 'FCP', y.sdhnum_0, 'AVC', y.srhnum_0, 'AVP', y.srhnum_0)),
            'AVC', (SELECT rtndat_0 FROM sreturn WHERE srhnum_0 = DECODE(x.gte_0, 'FAC', y.sdhnum_0, 'FCP', y.sdhnum_0, 'AVC', y.srhnum_0, 'AVP', y.srhnum_0)),
            'AVP', (SELECT rtndat_0 FROM sreturn WHERE srhnum_0 = DECODE(x.gte_0, 'FAC', y.sdhnum_0, 'FCP', y.sdhnum_0, 'AVC', y.srhnum_0, 'AVP', y.srhnum_0))
        ) AS date_piece_raw,
        x.num_0 AS fac,
        DECODE(SUBSTR(x.bpr_0, 1, 1), 'X', 'C', 'Y', 'C', 'Z', 'C', SUBSTR(x.bpr_0, 1, 1)) AS agence, 
        x.accdat_0 AS date_fac,
        x.bpr_0 AS tiers,
        y.itmref_0 AS article,
        y.itmdes1_0 AS lib_art_fac,
        y.tsicod_0 AS FC,
        y.tsicod_1 AS FT,
        y.tsicod_2 AS FD,
        y.gropri_0 AS tarif,
        DECODE(x.gte_0, 'FAC', y.qty_0, 'FCP', y.qty_0, 'AVC', y.qty_0 * -1, 'AVP', y.qty_0 * -1, 'AFV', y.qty_0 * -1) AS qte,
        DECODE(x.gte_0, 'FAC', (y.qty_0 * y.netpri_0 * x.ratmlt_0), 'FCP', (y.qty_0 * y.netpri_0 * x.ratmlt_0), 'AVC', (y.qty_0 * y.netpri_0 * x.ratmlt_0) * -1, 'AVP', (y.qty_0 * y.netpri_0 * x.ratmlt_0) * -1, 'AFV', (y.qty_0 * y.netpri_0 * x.ratmlt_0) * -1) AS HTN,
        DECODE(x.gte_0, 'FAC', (y.qty_0 * y.gropri_0 * x.ratmlt_0), 'FCP', (y.qty_0 * y.gropri_0 * x.ratmlt_0), 'AVC', (y.qty_0 * y.gropri_0 * x.ratmlt_0) * -1, 'AVP', (y.qty_0 * y.gropri_0 * x.ratmlt_0) * -1, 'AFV', (y.qty_0 * y.gropri_0 * x.ratmlt_0) * -1) AS HTB,
        SUBSTR(x.bpr_0, 2, 1) AS categ,
        (SELECT ' ' FROM bpcustomer f WHERE f.bpcnum_0 = x.bpr_0) AS xclasse,
        (SELECT t.tsicod_0 FROM itmmaster t WHERE t.itmref_0 = y.itmref_0) AS fcmkt,
        ' ' AS fclibmkt,
        (SELECT t.tsicod_1 FROM itmmaster t WHERE t.itmref_0 = y.itmref_0) AS ftmkt,
        ' ' AS ftlibmkt,
        (SELECT t.tsicod_2 FROM itmmaster t WHERE t.itmref_0 = y.itmref_0) AS fdmkt,
        ' ' AS fdlibmkt,
        ' ' AS proj,
        ' ' AS canal,
        ' ' AS sicda,
        ' ' AS artf,
        (SELECT MAX(u.bpsnum_0) FROM itmbps u WHERE u.itmref_0 = y.itmref_0) AS frs,
        (SELECT t.bpsnam_0 FROM bpsupplier t WHERE t.bpsnum_0 = (SELECT MAX(u.bpsnum_0) FROM itmbps u WHERE u.itmref_0 = y.itmref_0)) AS lib_frs2
    FROM sinvoice x, sinvoiced y 
    WHERE x.num_0 = y.num_0  
      AND x.accdat_0 BETWEEN '01/01/2017' AND '31/12/2026' 
      AND x.gte_0 <> 'AFV'
)
SELECT 
    DECODE(piece_raw, NULL, 'FORFAIT', ' ', 'FORFAIT', piece_raw) AS piece,
    DECODE(DECODE(piece_raw, NULL, 'FORFAIT', ' ', 'FORFAIT', piece_raw), 'FORFAIT', date_fac, date_piece_raw) AS date_piece,
    fac,
    agence,
    date_fac,
    trim(tiers),
    trim(article),
    trim(lib_art_fac),
    trim(FC),
    trim(FT),
    trim(FD),
    trim(fcmkt),
    trim(fclibmkt),
    trim(ftmkt),
    trim(ftlibmkt),
    trim(fdmkt),
    trim(fdlibmkt),
    tarif,
    qte,
    HTN,
    HTB,
    trim(categ),
    trim(proj),
    trim(canal),
    trim(sicda),
    trim(artf),
    trim(frs),
    trim(lib_frs2),
    trim(xclasse)
FROM base_data