create table datamart_detail_charges as select ACCNUM_0,TYP_0,NUM_0,JOU_0,ACCDAT_0,AAMM,FCY_0,ACC_0,SNS_0,AMTLED_0,MNT,CPT,TIERS,RACINE_CPT1,RACINE_CPT2,CODE_AG,CODECC,CHK_0,OFFACC_0,DECH,LIB_ECR,EXTOURNE from datamart_detail_charges_ancien union select ACCNUM_0,TYP_0,NUM_0,JOU_0,ACCDAT_0,AAMM,FCY_0,ACC_0,SNS_0,AMTLED_0,MNT,CPT,TIERS,RACINE_CPT1,RACINE_CPT2,CODE_AG,CODECC,CHK_0,OFFACC_0,DECH,LIB_ECR,EXTOURNE from datamart_detail_charges2020
/
exit
/
